#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — assistente de instalacao do Fadex Helpdesk.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

RAIZ="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$RAIZ"

MODO_SIMULADO=false   # --dry-run: mostra os comandos, nao executa nada
AUTOMATICO=false      # --yes: aceita todos os padroes, sem perguntar

uso() {
  cat <<'AJUDA'
Uso: ./setup.sh [opcoes]

Assistente de instalacao do Fadex Helpdesk. Escolhe portas livres, gera o
.env, sobe a stack com Docker Compose e verifica se a aplicacao respondeu.

Opcoes:
  --dry-run   Executa o fluxo inteiro sem tocar no Docker: imprime os comandos
              que seriam executados e simula os resultados.
  --yes       Aceita todos os padroes e nao faz perguntas.
  -h, --help  Mostra esta ajuda.

Variaveis de ambiente:
  ENV_FILE    Caminho do arquivo de ambiente gerado (padrao: .env).
AJUDA
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) MODO_SIMULADO=true ;;
    --yes|-y)  AUTOMATICO=true ;;
    -h|--help) uso; exit 0 ;;
    *) printf 'Opcao desconhecida: %s\n\n' "$1"; uso; exit 1 ;;
  esac
  shift
done

# ── Helpers proprios deste wizard ─────────────────────────────────────────

# pause — o --yes precisa ser realmente sem prompt, e banner() tambem chama
# pause(). Redefinimos aqui embaixo do marcador, sem tocar na biblioteca.
pause() {
  [[ "$AUTOMATICO" == true ]] && return 0
  printf '  %s%s%s ' "$DIM" "${1:-Pressione Enter para continuar}" "$RESET"
  read -r _ || true
}

# executar "descricao" comando... — roda o comando, ou apenas o imprime no
# modo simulado. Todo efeito colateral pesado passa por aqui.
executar() {
  local descricao="$1"; shift
  if [[ "$MODO_SIMULADO" == true ]]; then
    printf '  %s[simulado]%s %s\n' "$YELLOW" "$RESET" "$*"
    note "$descricao (nada foi executado)"
    return 0
  fi
  printf '  %s› %s%s\n' "$DIM" "$*" "$RESET"
  "$@"
}

# confirmar "pergunta" — igual a confirm(), mas responde sozinho no modo --yes.
confirmar() {
  if [[ "$AUTOMATICO" == true ]]; then
    printf '  %s? %s [y/N]%s nao (modo --yes)\n' "$DIM" "$1" "$RESET"
    return 1
  fi
  confirm "$1"
}

# ler_valor VARIAVEL "Pergunta" "padrao" — leitura livre, sem vinculo com o
# .env. No modo --yes devolve o padrao sem perguntar.
ler_valor() {
  local variavel="$1" pergunta="$2" padrao="${3:-}" entrada=""
  if [[ "$AUTOMATICO" == true ]]; then
    printf -v "$variavel" '%s' "$padrao"
    return 0
  fi
  if [[ -n "$padrao" ]]; then
    printf '  %s%s%s %s[%s]%s ' "$BOLD" "$pergunta" "$RESET" "$DIM" "$padrao" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$pergunta" "$RESET"
  fi
  read -r entrada || true
  [[ -z "$entrada" ]] && entrada="$padrao"
  printf -v "$variavel" '%s' "$entrada"
}

abortar() {
  printf '\n  %s✖ %s%s\n\n' "$RED" "$1" "$RESET"
  exit 1
}

# porta_em_uso NUMERO — verdadeiro quando alguem ja escuta na porta do host.
# A primitiva e o /dev/tcp do proprio bash: funciona em Linux, macOS e no Git
# Bash do Windows, sem depender de ss, lsof ou nc.
porta_em_uso() {
  local porta="$1"
  if command -v timeout >/dev/null 2>&1; then
    timeout 1 bash -c "exec 3<>/dev/tcp/127.0.0.1/${porta}" >/dev/null 2>&1 && return 0
    return 1
  fi
  (exec 3<>"/dev/tcp/127.0.0.1/${porta}") >/dev/null 2>&1 && return 0
  return 1
}

# sonda_disponivel — o bash sabe abrir sockets? Alguns pacotes compilam o bash
# sem /dev/tcp, e ai "porta livre" na verdade significa "nao consegui sondar".
# Vale a pena dizer isso ao usuario em vez de prometer o que nao foi checado.
sonda_disponivel() {
  local erro
  erro=$( (exec 3<>"/dev/tcp/127.0.0.1/1") 2>&1 || true )
  [[ "$erro" != *"No such file"* && "$erro" != *"nao existe"* && "$erro" != *"existe"* ]]
}

# quem_ocupa NUMERO — enfeite opcional: tenta descobrir o processo dono da
# porta. So funciona onde ss ou lsof existem; o wizard nunca depende disso.
quem_ocupa() {
  local porta="$1" dono=""
  if command -v lsof >/dev/null 2>&1; then
    dono=$(lsof -nP -iTCP:"$porta" -sTCP:LISTEN -Fc 2>/dev/null | grep '^c' | head -n1 || true)
    dono="${dono#c}"
  elif command -v ss >/dev/null 2>&1; then
    dono=$(ss -ltnp 2>/dev/null | grep -E "[:.]${porta}[[:space:]]" | grep -oE '"[^"]+"' | head -n1 || true)
    dono="${dono//\"/}"
  fi
  printf '%s' "$dono"
}

# true quando o ENV_FILE ja existia antes desta execucao. So nesse caso as
# portas gravadas nele valem como "escolha anterior" — um .env recem-copiado do
# .env.example carrega apenas os padroes, que precisam ser testados de verdade.
ENV_PREEXISTIA=false

PORTAS_RESERVADAS=()   # portas ja atribuidas nesta execucao
CHAVES_PORTA=()        # nomes das variaveis, na ordem da tabela
ROTULOS_PORTA=()
PADROES_PORTA=()
MOTIVOS_PORTA=()       # vazio quando a porta ficou no valor pretendido

porta_reservada() {
  local porta="$1" reservada
  for reservada in ${PORTAS_RESERVADAS[@]+"${PORTAS_RESERVADAS[@]}"}; do
    [[ "$reservada" == "$porta" ]] && return 0
  done
  return 1
}

porta_valida() {
  [[ "$1" =~ ^[0-9]+$ ]] && (( $1 >= 1 && $1 <= 65535 ))
}

# resolver_porta CHAVE PADRAO "Rotulo" — parte do valor ja salvo no .env (ou
# do padrao), testa e incrementa de 1 em 1 ate achar uma porta livre. Uma porta
# ocupada e aceita quando ja e a porta gravada para este proprio servico: numa
# reexecucao quem esta escutando nela e a stack do proprio projeto.
resolver_porta() {
  local chave="$1" padrao="$2" rotulo="$3"
  local atual candidato pretendida motivo="" tentativas=0 dono=""
  atual=$(_existing "$chave" || true)
  porta_valida "${atual:-0}" || atual=""
  [[ "$ENV_PREEXISTIA" == true ]] || atual=""
  candidato="${atual:-$padrao}"
  pretendida="$candidato"

  while true; do
    if porta_reservada "$candidato"; then
      if [[ -z "$motivo" ]]; then
        motivo="porta ${pretendida} ja atribuida a outro servico nesta execucao"
      fi
    elif [[ "$candidato" != "$atual" ]] && porta_em_uso "$candidato"; then
      if [[ -z "$motivo" ]]; then
        dono=$(quem_ocupa "$candidato")
        if [[ -n "$dono" ]]; then
          motivo="porta ${pretendida} ocupada por ${dono}"
        else
          motivo="porta ${pretendida} ocupada na maquina"
        fi
      fi
    else
      # porta ocupada mas identica a que ja estava gravada: numa reexecucao
      # quem escuta nela e a propria stack, entao mantemos e avisamos.
      if [[ -z "$motivo" && "$candidato" == "$atual" ]] && porta_em_uso "$candidato"; then
        motivo="mantida (${candidato} ocupada, provavelmente pela propria stack)"
      fi
      break
    fi
    candidato=$((candidato + 1))
    tentativas=$((tentativas + 1))
    (( tentativas > 200 )) && abortar "Nao encontrei porta livre para ${rotulo} a partir de ${pretendida}."
    porta_valida "$candidato" || abortar "Nao encontrei porta livre para ${rotulo}."
  done

  # valor herdado do .env que nao e o padrao: nao foi deslocado agora
  if [[ -z "$motivo" && "$candidato" != "$padrao" ]]; then
    motivo="mantida do ${ENV_FILE}"
  fi

  PORTAS_RESERVADAS+=("$candidato")
  CHAVES_PORTA+=("$chave")
  ROTULOS_PORTA+=("$rotulo")
  PADROES_PORTA+=("$padrao")
  MOTIVOS_PORTA+=("$motivo")
  printf -v "$chave" '%s' "$candidato"
}

# tabela_portas — mostra o que foi escolhido e por que algo saiu do padrao.
tabela_portas() {
  local i chave valor motivo
  printf '  %s%-4s %-24s %-10s %s%s\n' "$BOLD" "#" "Servico" "Porta" "Observacao" "$RESET"
  for i in "${!CHAVES_PORTA[@]}"; do
    chave="${CHAVES_PORTA[$i]}"
    valor="${!chave}"
    motivo="${MOTIVOS_PORTA[$i]}"
    if [[ "$motivo" == mantida* || "$motivo" == ajustada* ]]; then
      printf '  %-4s %-24s %s%-10s%s %s\n' \
        "$((i + 1))" "${ROTULOS_PORTA[$i]}" "$GREEN" "$valor" "$RESET" "$motivo"
    elif [[ -n "$motivo" ]]; then
      printf '  %-4s %-24s %s%-10s%s deslocada: %s\n' \
        "$((i + 1))" "${ROTULOS_PORTA[$i]}" "$YELLOW" "$valor" "$RESET" "$motivo"
    else
      printf '  %-4s %-24s %s%-10s%s padrao %s\n' \
        "$((i + 1))" "${ROTULOS_PORTA[$i]}" "$GREEN" "$valor" "$RESET" "${PADROES_PORTA[$i]}"
    fi
  done
}

# ajustar_portas — permite trocar uma porta individualmente, com nova validacao.
ajustar_portas() {
  local indice chave nova anterior i reservada
  local restantes
  while true; do
    ler_valor indice "Numero da porta a ajustar (Enter para seguir):" ""
    [[ -z "$indice" ]] && return 0
    if ! [[ "$indice" =~ ^[0-9]+$ ]] || (( indice < 1 || indice > ${#CHAVES_PORTA[@]} )); then
      warn "Escolha um numero entre 1 e ${#CHAVES_PORTA[@]}."
      continue
    fi
    i=$((indice - 1))
    chave="${CHAVES_PORTA[$i]}"
    anterior="${!chave}"
    ler_valor nova "Nova porta para ${ROTULOS_PORTA[$i]}:" "$anterior"
    if ! porta_valida "$nova"; then
      warn "Porta invalida: ${nova}."
      continue
    fi
    if [[ "$nova" != "$anterior" ]]; then
      if porta_reservada "$nova"; then
        warn "A porta ${nova} ja foi atribuida a outro servico nesta execucao."
        continue
      fi
      if porta_em_uso "$nova"; then
        warn "A porta ${nova} esta ocupada na maquina."
        confirmar "Usar ${nova} mesmo assim?" || continue
      fi
    fi
    # libera a porta antiga da reserva e registra a nova
    restantes=()
    for reservada in "${PORTAS_RESERVADAS[@]}"; do
      [[ "$reservada" == "$anterior" ]] || restantes+=("$reservada")
    done
    PORTAS_RESERVADAS=(${restantes[@]+"${restantes[@]}"} "$nova")
    printf -v "$chave" '%s' "$nova"
    MOTIVOS_PORTA[$i]="ajustada manualmente"
    say "OK: ${ROTULOS_PORTA[$i]} agora usa ${nova}."
  done
}

# gerar_segredo — 48 bytes aleatorios em base64. Tenta openssl, cai para
# /dev/urandom e, em ultimo caso, para o $RANDOM do bash. O backend exige pelo
# menos 32 caracteres, entao os tres caminhos passam por essa checagem.
gerar_segredo() {
  local segredo=""
  if command -v openssl >/dev/null 2>&1; then
    segredo=$(openssl rand -base64 48 2>/dev/null | tr -d '\n' || true)
  fi
  if (( ${#segredo} < 32 )) && [[ -r /dev/urandom ]]; then
    segredo=$(head -c 48 /dev/urandom | base64 | tr -d '\n' || true)
  fi
  while (( ${#segredo} < 64 )); do
    segredo="${segredo}$(printf '%04x' $((RANDOM)))"
  done
  printf '%s' "$segredo"
}

# esperar_http URL SEGUNDOS "Rotulo" — o backend e o frontend nao tem
# healthcheck no compose, entao a espera e por polling ate responderem HTTP.
esperar_http() {
  local url="$1" limite="$2" rotulo="$3" decorrido=0 codigo=""
  if [[ "$MODO_SIMULADO" == true ]]; then
    printf '  %s[simulado]%s aguardando %s em %s\n' "$YELLOW" "$RESET" "$rotulo" "$url"
    return 0
  fi
  if ! command -v curl >/dev/null 2>&1; then
    warn "curl indisponivel — pulei a verificacao de ${rotulo} (${url})."
    return 0
  fi
  printf '  aguardando %s' "$rotulo"
  while (( decorrido < limite )); do
    codigo=$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "$url" || true)
    if [[ "$codigo" =~ ^[234] ]]; then
      printf ' %s✓ respondeu (HTTP %s)%s\n' "$GREEN" "$codigo" "$RESET"
      return 0
    fi
    printf '.'
    sleep 3
    decorrido=$((decorrido + 3))
  done
  printf ' %s✖%s\n' "$RED" "$RESET"
  warn "${rotulo} nao respondeu em ${limite}s. Veja os logs com: docker compose logs -f"
  return 1
}

# ── Estagio 1 · Pre-requisitos ────────────────────────────────────────────

banner "Instalacao do Fadex Helpdesk"

stage "Pre-requisitos"
say "Conferindo o Docker antes de qualquer outra coisa."
if [[ "$MODO_SIMULADO" == true ]]; then
  warn "Modo simulado: nenhum comando do Docker sera executado."
fi

command -v docker >/dev/null 2>&1 \
  || abortar "Docker nao encontrado. Instale o Docker Engine ou o Docker Desktop e rode novamente."
say "Docker encontrado: $(docker --version 2>/dev/null || echo desconhecido)"

docker compose version >/dev/null 2>&1 \
  || abortar "Plugin 'docker compose' nao encontrado. Instale o Docker Compose v2 (docker-compose-plugin)."
say "Compose encontrado: $(docker compose version --short 2>/dev/null || echo desconhecido)"

docker info >/dev/null 2>&1 \
  || abortar "O daemon do Docker nao esta respondendo. Inicie o Docker e rode novamente."
say "Daemon do Docker respondendo."

[[ -f docker-compose.yml ]] \
  || abortar "Rode este script na raiz do repositorio (docker-compose.yml nao encontrado)."
if [[ -f "$ENV_FILE" ]]; then
  ENV_PREEXISTIA=true
  note "Encontrei ${ENV_FILE}: vou reaproveitar o que ja estiver la."
elif [[ -f .env.example ]]; then
  cp .env.example "$ENV_FILE"
  note "Criei ${ENV_FILE} a partir de .env.example."
fi

if ! sonda_disponivel; then
  warn "Este bash foi compilado sem /dev/tcp: nao consigo testar portas."
  warn "Vou propor as portas padrao; ajuste manualmente se alguma estiver ocupada."
fi
printf '\n'
pause "Tudo certo. Enter para escolher as portas."

# ── Estagio 2 · Portas ────────────────────────────────────────────────────

stage "Portas"
say "Testo cada porta padrao e, se estiver ocupada, subo de 1 em 1 ate achar uma livre."
printf '\n'

resolver_porta BACKEND_PORT      8080  "Backend (API)"
resolver_porta FRONTEND_PORT     3000  "Frontend (web)"
resolver_porta POSTGRES_PORT     5432  "PostgreSQL"
resolver_porta MAILPIT_UI_PORT   8025  "Mailpit (interface)"
resolver_porta MAILPIT_SMTP_PORT 1025  "Mailpit (SMTP)"
resolver_porta OLLAMA_PORT       11434 "Ollama"

tabela_portas
printf '\n'
note "Postgres, Mailpit e Ollama conversam por dentro da rede do compose;"
note "mudar a porta deles muda so o endereco de visita a partir do host."
printf '\n'

if confirmar "Quer ajustar alguma porta manualmente?"; then
  ajustar_portas
  printf '\n'
  tabela_portas
  printf '\n'
fi

write_env BACKEND_PORT      "$BACKEND_PORT"
write_env FRONTEND_PORT     "$FRONTEND_PORT"
write_env POSTGRES_PORT     "$POSTGRES_PORT"
write_env MAILPIT_UI_PORT   "$MAILPIT_UI_PORT"
write_env MAILPIT_SMTP_PORT "$MAILPIT_SMTP_PORT"
write_env OLLAMA_PORT       "$OLLAMA_PORT"

# Acoplamentos: a URL da API entra na imagem do frontend como build arg e o
# CORS do backend precisa liberar a porta real do frontend. Os dois sao sempre
# recalculados a partir das portas escolhidas — nunca perguntados.
API_BASE_URL="http://localhost:${BACKEND_PORT}/api/v1"
ORIGENS_CORS="http://localhost:${FRONTEND_PORT},http://127.0.0.1:${FRONTEND_PORT}"
URL_FRONTEND="http://localhost:${FRONTEND_PORT}"
write_env NEXT_PUBLIC_API_BASE_URL "$API_BASE_URL"
write_env CORS_ALLOWED_ORIGINS     "$ORIGENS_CORS"
# Usada nos links dos e-mails de notificacao: sem derivar, o e-mail aponta para
# uma porta onde nao ha nada.
write_env FRONTEND_BASE_URL        "$URL_FRONTEND"
printf '\n'
pause "Enter para gerar o segredo da aplicacao."

# ── Estagio 3 · Segredo e valores derivados ───────────────────────────────

stage "Segredo e valores derivados"
JWT_SECRET=$(_existing JWT_SECRET || true)
if [[ -z "$JWT_SECRET" || "$JWT_SECRET" == trocar-por-* ]]; then
  JWT_SECRET=$(gerar_segredo)
  say "Gerei um JWT_SECRET novo."
else
  say "Reaproveitei o JWT_SECRET ja gravado em ${ENV_FILE}."
fi
write_env JWT_SECRET "$JWT_SECRET"
write_env AI_TRIAGE_ENABLED true
printf '\n'

say "A triagem por IA fica ligada. Ela pode usar modelos locais do Ollama"
say "(llama3.2:1b e all-minilm, mais de 1 GB de download) ou seguir sem eles."
note "Sem os modelos a classificacao continua funcionando pela heuristica do"
note "FallbackTicketClassifier — o download nao e obrigatorio."
printf '\n'
BAIXAR_MODELOS=false
if confirmar "Baixar os modelos do Ollama depois que a stack subir?"; then
  BAIXAR_MODELOS=true
fi
printf '\n'
pause "Enter para revisar o ${ENV_FILE}."

# ── Estagio 4 · Revisao (ultimo ponto sem efeito colateral) ───────────────

stage "Revisao"
say "Ate aqui o script so escreveu ${ENV_FILE}. Nenhum container foi tocado."
printf '\n'
grep -E '^(BACKEND_PORT|FRONTEND_PORT|POSTGRES_PORT|MAILPIT_UI_PORT|MAILPIT_SMTP_PORT|OLLAMA_PORT|NEXT_PUBLIC_API_BASE_URL|CORS_ALLOWED_ORIGINS|FRONTEND_BASE_URL|AI_TRIAGE_ENABLED|JWT_SECRET)=' "$ENV_FILE" \
  | sed -E 's/^(JWT_SECRET=).*/\1********/' \
  | sed 's/^/    /'
printf '\n'
if [[ "$BAIXAR_MODELOS" == true ]]; then
  note "Modelos do Ollama: serao baixados no estagio 6."
else
  note "Modelos do Ollama: nao serao baixados (a heuristica de fallback assume)."
fi
printf '\n'
if [[ "$AUTOMATICO" == true ]]; then
  note "Modo --yes: seguindo sem confirmacao."
else
  confirm "Subir a stack com esses valores?" \
    || abortar "Cancelado por voce. O ${ENV_FILE} ficou salvo; rode ./setup.sh de novo quando quiser."
fi

# ── Estagio 5 · Subida da stack ───────────────────────────────────────────

stage "Subida da stack"
say "A URL da API entra na imagem do frontend como build arg, entao a subida"
say "sempre usa --build: se a porta do backend mudou, a imagem precisa ser refeita."
printf '\n'
# O servico ollama-models nao tem 'profiles' no compose: num 'up' generico ele
# entraria junto e o download de mais de 1 GB aconteceria sem ser perguntado.
# Por isso a lista de servicos aqui e explicita.
if ! executar "Sobe postgres, mailpit, ollama, backend e frontend." \
     docker compose up -d --build postgres mailpit ollama backend frontend; then
  printf '\n'
  warn "O 'docker compose up' falhou."
  warn "A causa mais comum e uma porta que ficou ocupada entre a escolha e a subida."
  warn "Veja o erro acima, libere a porta e rode ./setup.sh de novo — o ${ENV_FILE} ja esta salvo."
  abortar "Nao consegui subir a stack."
fi
printf '\n'
pause "Enter para seguir."

# ── Estagio 6 · Modelos do Ollama ─────────────────────────────────────────

stage "Modelos do Ollama"
MODELOS_FALHARAM=false
if [[ "$BAIXAR_MODELOS" == true ]]; then
  say "Baixando os modelos agora que o container do Ollama esta de pe."
  warn "Sao mais de 1 GB; pode demorar bastante na primeira vez."
  # O download e opcional: se falhar, avisamos e seguimos para a verificacao.
  if ! executar "Baixa llama3.2:1b e all-minilm no volume do Ollama." \
       docker compose run --rm ollama-models; then
    warn "O download dos modelos falhou. A stack continua de pe."
    warn "A classificacao segue pela heuristica do FallbackTicketClassifier."
    warn "Para tentar de novo: docker compose run --rm ollama-models"
    MODELOS_FALHARAM=true
  fi
else
  say "Pulando o download dos modelos."
  note "A classificacao segue pela heuristica do FallbackTicketClassifier."
  note "Para baixar depois: docker compose run --rm ollama-models"
fi
printf '\n'
pause "Enter para verificar se a aplicacao respondeu."

# ── Estagio 7 · Verificacao e resumo ──────────────────────────────────────

stage "Verificacao"
say "Postgres e Mailpit tem healthcheck no compose; backend e frontend nao."
say "A checagem deles e por polling ate responderem HTTP."
printf '\n'
BACKEND_OK=true
FRONTEND_OK=true
esperar_http "http://localhost:${BACKEND_PORT}/v3/api-docs" 240 "backend" || BACKEND_OK=false
esperar_http "http://localhost:${FRONTEND_PORT}" 120 "frontend" || FRONTEND_OK=false
printf '\n'
pause "Enter para ver o resumo."

# finish() limpa a tela, entao o resumo util precisa vir depois dele.
finish

printf '  %s%sAcesse%s\n' "$BOLD" "$BLUE" "$RESET"
say "Aplicacao ........ http://localhost:${FRONTEND_PORT}"
say "API .............. http://localhost:${BACKEND_PORT}/api/v1"
say "Swagger .......... http://localhost:${BACKEND_PORT}/swagger-ui.html"
say "Mailpit .......... http://localhost:${MAILPIT_UI_PORT}"
printf '\n  %s%sCredenciais do seed%s\n' "$BOLD" "$BLUE" "$RESET"
say "ADMIN ............ admin@fadex.org.br / admin123"
say "SOLICITANTE ...... solicitante@fadex.org.br / solicitante123"
printf '\n  %s%sComandos uteis%s\n' "$BOLD" "$BLUE" "$RESET"
say "Logs ............. docker compose logs -f"
say "Status ........... docker compose ps"
say "Derrubar ......... docker compose down"
say "Derrubar + dados . docker compose down -v"
printf '\n  %s%sRodar de novo%s\n' "$BOLD" "$BLUE" "$RESET"
say "Linux/macOS ...... ./setup.sh"
say "Windows .......... ./setup.sh no Git Bash ou no WSL (ou clique em setup.cmd)"
note "make setup e so um atalho para quem tem make instalado; ./setup.sh e o caminho oficial."
printf '\n'
if [[ "$MODO_SIMULADO" == true ]]; then
  warn "Execucao simulada: nenhum container foi criado."
else
  [[ "$BACKEND_OK" == true && "$FRONTEND_OK" == true ]] \
    || warn "Algum servico nao respondeu a tempo. Cheque com: docker compose logs -f"
  if [[ "$MODELOS_FALHARAM" == true ]]; then
    warn "Os modelos do Ollama nao foram baixados; a heuristica de fallback assume."
  fi
fi
printf '\n'
