spring.application.name=helpdesk
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

server.port=${SERVER_PORT:8080}

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
