spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fadex_helpdesk}
spring.datasource.username=${DB_USERNAME:fadex}
spring.datasource.password=${DB_PASSWORD:fadex}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=${JPA_SHOW_SQL:false}

logging.level.br.org.fadex.helpdesk=${APP_LOG_LEVEL:DEBUG}
logging.level.org.flywaydb=${FLYWAY_LOG_LEVEL:INFO}
logging.level.org.springframework.security=${SECURITY_LOG_LEVEL:INFO}
